matrix:
  include:
  - os: linux
    sudo: true
    dist: trusty
  - os: linux
    sudo: true
    dist: xenial
language: python
python:
- '3.6'
before_install: 
install:
- pip3 install -r requirements.txt
- pyinstaller --version
- pyinstaller -y helloworld.py
script: "./dist/helloworld/helloworld"
deploy:
  provider: releases
  prerelease: true
  file_glob: true
  file:
  - dist/helloworld/helloworld
  on:
    repo: pocc/test-repo
    dist: xenial
    tags: true
  skip_cleanup: true
  api_key:
    secure: "YY52ywh7AW+0HYcDWaA3puEDVN3VLzQPyhSwhfuZ29YAZcEXYGIitnjWRlRcuGK8c3/UR8W+c834Ru6AgDJvpds3GczfwL2xpVcFa6hu3HNCc7ReLmK9phmuCxHJS1Gelv/jJUMNSBSnmxmNQvtjuEVhrjeC6Drulz3FQXP/eu6Qm9/uuKt6kdztPWOpeymAGwrg9o1JpK4jVsmam4Nke1Uv/6QQVh0V6QqfFXJEaTRNr2AHj3XJPe//7X9N8pgr10AEqYHDZ28wlj6HbyNcBBe7rBDai7UpmiCD4/lILScI+fpXXQFNlsSzXq1hS5oNYLJHbM1RjCQjGePRvvEuD/2MEfmjsNV6NQOEhHvSMYV1S2oLzkjqFP54GccYzW3+W8+UL03405EPu1CBJ4QUilpmaBFOIfl5TppDDC6Jc0RaIHbzI/qBLFV33lrMb8BPST5vhsRiqv+msy5JQ6mT2AVVHyiAYmhWFoNGiAgZGSJeCiMCJtbVb7y1tteBWM/mBnvj8wFWyV/qzoIh+Yz91VZ9aNZNSLKURjhpN1VGQ191qlwSq2wJXp6ih1xpJ3GSRIuR8w8pe/44JAZnLlIUVICbkIfkHzoYkLrt2OTCfhB2Fv4Vfej6USSZRMIbu59MoUoXeEw7QexyYAx6R8OkadVAzn9P4HKKIukbm9SXeT8="
  username:
    secure: "gWj4jPbo6EHx1lkH/2eyeatYZifPzsVG00N6asH9K4fqr577pRr2UOpOuK0dUmhjTN2lbEMFfoa+WECbDnnlhRAtKpWZdXQ28tBEMuZoJh/Xfx725/15Y5q8XXtROUOQ/SeeIXeN9Wak9dyfZpGCA9fYMYe7ldwEU0jC/cLdhHklbTTq8+UhP+HZlLJqZ4HilmyEb/F1HpHCXBP+oI3zW9a2KZuqwgjNJ2/u60Z6YNFIxtAY3S8qRV2+u261GsETB4bsU16xEx0g4p5DUBTGOhRanhVecUW6Y82iiDv9o7UjIMEAIDHKgB0oYtF7yWbK0bWcaV3hNNh4AcaVlhapdYmOcg/vO4eXrLRroGQ/4SWKjupbipjgn1DazRfQDW7dIv8AFfgsJwX+w2d8waciPMaM2XMGFhFCawtfD2po6zv7Kq+SWdR0RLTIvLIenrdDY+36T3VxqQHuj6Xvr8QXoiyuPGd6GIjfwF5nUxEc2ItvBDXjbP6SuKOBmNBZZUrq6HgkXbQ31D0AtcaQBn87BcVLVYzr6NqDd+p18u9+FOgWxLH8ibiVh00UYAsdptig0fe3HETP72C7sZBMSWhnUPeLrOyemjQQLETlf3FSb0Gd3F4Dr3CMXbuMWcDvParxDIG6Ke/jiferh1UhAgVjynlSo+6AK0rc2ZRQQ1HpCI8="
  password:
    secure: "DE/AltcHc4o99JRALziq55q/KO2pwop/2MBBInPcFbYMjybCYrgFRxL+RvFhJymvuXuXPal2udBrIs+kE9Vt+TA4q32VOSCBjYw3XIN8vhTox/CuxmtJDo/OxxJ1miJXmI2o90gN1zOey5xGDX0pp5OGoblCdcLlerAmHNptP2y9GK0tSkLY/MaHaVEKny+1qcI88WWZLhyavIHPhqFlVjGBQeSj5u3FUwi1NmdiZqhhVnSSFNTr/2P6GzdqN0NnQr0QeeREsmKwC/s523A1I9PkxKXE/XaCT8BJum9q34wPPFiTcojY29XGOv9JlysDWMc7y1uGQPTcyuPIasHKJie/2FaVQ4hq8b6IAloIbVXKW565mkYRihReX7XWT0FPIkV4KSKVqbv8Is4loLH+it84LiNWxYJdbfr3brJ+3caZFvbtecOn1FW25hz0QWbn23ex7bQ9O9OvrZMMFhk7NplA9fllwPhBr3HRjTJ1z+Ed+dKnryspca6+wkPL+rHe2BtzvvBSDJFY5/FvKStz4Lu/7twVuWN5rXb/Pt9+PqBTrtyXJP9gok0iJ2OTPf/UatSuRAdrKGT95fZiF8e80wGORSDZxZWsx/ri4jMkqtSiLDwj4Qm5Vqu/iOBj5Sr8iSkeqB0i/a638QuivpuKf9OgF85ZFnZuOniZwOcWpiI="
