matrix:
  include:
  - os: linux
    sudo: true
    dist: trusty
  - os: linux
    sudo: true
    dist: xenial

language: python
python:
- '3.6'

# Only tagged commits
branches:
  only:
  - master

before_install:
  - sudo apt update

install:
  - sudo apt install python3 python3-pip
  - /usr/bin/python3 -m pip install -U pip
  - /usr/bin/python3 -m pip install -r requirements.txt
  - pyinstaller --version
  - pyinstaller -y helloworld.py

script: ./dist/helloworld/helloworld
