matrix:
  include:
  - os: linux
    sudo: true
    dist: trusty
  - os: linux
    sudo: true
    dist: xenial
language: python
python:
- '3.6'
before_install: 
install:
- pip3 install -r requirements.txt
- pyinstaller --version
- pyinstaller -y helloworld.py
script: "./dist/helloworld/helloworld"
deploy:
  provider: releases
  prerelease: true
  file_glob: true
  file:
  - dist/helloworld/helloworld
  on:
    repo: pocc/test-repo
    dist: xenial
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: WlKQOccxLh+Xsf8ez4H/BjGSa/HTdk71+A7kSMB4NpiKVK9hsP/HgmkYS3TxzIsEwVCFufD8NVmjjEf5ORVA3FP19fM2CLFu5QGfyoa1G1z660LqKO8pnwSboamzbJYKxSVgXYRvveik8HxAWhLizk7ozXvVbi/S6rt7jNpjHpfIU4xFTzd3wu5YAb8CiSXVKZtyAKyOECkihjgwDqIrmsQf+uD4Dr/h2yBCKApQHpS23ugWvTztcXHqgv62mIKI7RZsM/1B8JKE1xoISk8VJoyCy7ghgykTDIUB5ZlARB4hESaaCIZ1l5ro8wEnIyNHonKFE++u3ASdm1SPrG8vBH1uW03ziRI04RviZ5l/EcN+U8X0AotL+wgqu+rM5E0aCK+XM/Dxsk4qqbeB79+YiIOGou5GxzBHLl7KHU808/gdvjeEAM6Ac/epiUI8H2DNdVw1xXQcHsG7TocpKE0Kjhjo62VA+wuHgM4Md+CUX9AL2OTRL5nbwm5mYvD5uX+K8XiNx1zZBzbC/z7vqDJfpN+iUv3jMYbNQHn2sp1pBn5qDw5zZtt4YmnC889HD9m7idivZBGwrG889ZWlOWOopPe/8LTJ8v+DFly49rjVIw5WEVayyI/QBP1/g/i/fCV663FnPtUqPcDCnoDa1ZwIcMa/5+qgUGDnJAkDfhHib80=
  - secure: h/kjZlCmtYcUlmCB5Fm8ThLm4yKW5VLRCG6AVnmIhnWmKlH9PQ3x5nm0sV47oG6TlvWQR8l0lOonw8PVNZNmMqWn4pclkybZulgVcWSJNBSdWUGUTsAHj1llBlX3+XdeHresSnNV8zFVRBF1/8LJkoXywOZbAxl0Te8x9iouJ4kEHk4TM41jpASh+KvCRWvX9Y4yVL/iBftJe7fxxu4KFv7luSL1TiY0J5TLcWMcD6u1ux3dFfVbtEzuBzw0D2LxyVuRLP0c+K59Ne/qjM2ymwW8PMN/DZMTlrDwJf/gtI6BkHedle9mxTvF9mlCx0rLFudZDxagC8ZzDgeyGLWJOpUg9LN7GOT02Ly30lkKiqQERw3jaoxUz1qQFxPCad8gXyioZCk0iWE5PNHb3gftI/8tJeno/XG+uXbCWsHuw2rgsRHYjh3ThtSJOhEtFf8uFS8E0m+/x1TCqlMUFW55rK+dgHqSJLeCONPLz3i0pbv2HGixYSYP+dfiEomn5QncTO6KW0IDYI9Y4+vIP9B4SCsGNenNVvWhxVFtpV4543yZ0e+2xxtSo3EHLOvwohYTm2WBIlLyey/ZRuPBcUTNXXEP4DHhgIVMxe6SYV6zA+0W4oaHHJ5HR7x5CJApAhRNdxzCOcamVkDdBT25eG575ZivwRGFs7mY77s0WmZrjHc=
  - secure: GnkfmsO4llxHEItz4pCOZLzBXNHQGAGuv07MYceW/gM1plaMUTskpVEtq3B/5xqOYB6UTUU5b/1VLoqmhtFeY4uy/1Bf6eeN8KUBydwHhV/Hu8pNSyc4cm9k80X0B7iDLwi0/f0MNaaSyLufg6DhSsmYCmthAPWixC699lAQT3VFA8KRQ87pAXygkSSUbsvMC7lBSWRcrafqVzuLUHoH7Xzl8PZdFMsQH2JuOGqwRzVMsFEYlzb0DTTmaS/Z3bS5gR/IFRI0dt5IetBDNvgFpaPut39weDG0GDD6xpLcWsMmOgGv5HV44/wS6zMyVB6QjumC3HgSN9lkaEBxjHgAKyrkqorfc6h2HufuWkNG/4R4IplyneULjLC1s8CjbevNjL+UAst+46M04tK9zpNGSiPpiGFHJ/aJ3/6xY2e1j9dKOK/rJgiLSVbt6XM7BQBpfCLftzmu7Ka0LcyuvZTxPIXpnp107vzyUbE7uQ68Vbg7tcK8FywfuPJTff/Zfg33XaopX++21a+lGzIX7PMIaLU9/r52PR6eEpzGS5w8sZJw3GdZqCUOK8SEJJ5eE8k0uDKy5pZcx27pCZjHtCkHeAs/SEKXDibU+4450/Tm+fh3Iy9juTXvrBQvVFiGk991W8SR8gCFpadyajnznGEmOadVaQf/eRLKYIQg6cZbhEA=
